package com.nbshome.lawtrakticketsapp.enums;


public enum Country
{
    AA("Albania"),
    AD("Andorra"),
    AE("Anguilla"),
    AF("Afghanistan"),
    AH("Ashmore & Cartier Islands"),
    AI("Antigua & Barbuda"),
    AJ("Aruba"),
    AN("Algeria"),
    AO("Angola"),
    AP("Armenia"),
    AQ("Azores Islands"),
    AS("Australia"),
    AT("Argentina"),
    AU("Austria"),
    AV("Azerbaijan"),
    BB("Barbados"),
    BD("Bahamas"),
    BE("Bahrain/Bahrein"),
    BF("Bassas Da India"),
    BG("Belgium"),
    BH("Belize/British Honduras"),
    BI("Burundi"),
    BL("Bangladesh"),
    BM("Bermuda"),
    BN("Bhutan"),
    BO("British Indian Ocean Territory"),
    BP("Bosnia & Hercegovena"),
    BQ("Bouvet Island"),
    BR("Burma"),
    BS("British Solomon Islands/Solomon Islands"),
    BT("Botswana"),
    BU("Bulgaria"),
    BV("Bolivia"),
    BW("Balearic Islands"),
    BX("Brunei"),
    BY("Byelarus"),
    BZ("Brazil"),
    CB("Colombia"),
    CC("Cuba"),
    CD("Canada"),
    CF("Chad"),
    CJ("Cambodia/Kampuchea/Kmer Republic"),
    CK("Czechoslovakia"),
    CM("Cameroon"),
    CP("Cayman Islands"),
    CQ("Chile"),
    CR("Costa Rica"),
    CS("Cyprus"),
    CV("Cape Verde Islands"),
    CW("Central African Republic"),
    CY("Ceylon/Sri Lanka"),
    DB("Clipperton Island"),
    DD("Cocos Islands/Keeling Islands"),
    DG("Comoros/Comoros Islands"),
    DH("Benin/Dahomey"),
    DI("Cook Islands"),
    DJ("Coral Sea Islands"),
    DK("Denmark"),
    DM("Dominica"),
    DN("Djibouti"),
    DR("Dominican Republic"),
    DU("Ducie Islands"),
    EK("Equatorial Guinea"),
    EL("El Salvador"),
    EM("East Germany/German Democratic Republic"),
    EN("England"),
    EO("Ethiopia"),
    ER("Europa Island"),
    ES("Estonia"),
    EU("Ecuador"),
    EY("Egypt/United Arab Republic"),
    EZ("Czech Republic"),
    FA("Falkland Islands"),
    FD("Finland"),
    FG("French Guiana"),
    FJ("Fiji"),
    FN("France"),
    FO("Faroe Islands"),
    FP("French Polynesia"),
    FR("French Southern and Antarctic Lands"),
    FS("Federated States of Micronesia"),
    GB("Gabon"),
    GC("Greece"),
    GD("Georgia"),
    GE("Germany"),
    GF("Guernsey"),
    GG("Ghana"),
    GI("Guinea"),
    GJ("Grenada"),
    GK("Gambia"),
    GN("Greenland"),
    GO("Glorioso Islands"),
    GP("Guadeloupe"),
    GS("South Georgia and the South Sandwich Islands"),
    GT("Guatemala"),
    GY("Guyana"),
    GZ("Gaza"),
    HC("Hercegovenia"),
    HD("Honduras"),
    HE("Heard Island/McDonald Island"),
    HK("Hong Kong"),
    HN("New Hebrides/Vanuatu"),
    HR("Christmas Island"),
    HS("Saint Helena"),
    HT("Haiti"),
    HU("Hungary"),
    IB("Isle of Man"),
    IC("Iceland"),
    IE("Ireland"),
    II("India/Sikkim"),
    IM("Madeira Islands"),
    IO("Indonesia/Portugese Timor"),
    IQ("Iraq"),
    IR("Iran"),
    IS("Israel"),
    IT("Italy/Sardinia/Sicily"),
    IU("Niue"),
    IY("Ivory Coast"),
    JA("Japan"),
    JE("Jersey"),
    JM("Jamaica"),
    JN("Jan Mayen"),
    JO("Jordan"),
    JU("Juan de Nova Island"),
    KB("Gilbert Islands/Kiribati"),
    KC("Croatia"),
    KE("Kenya"),
    KH("Manahiki Island"),
    KN("North Korea"),
    KO("South Korea"),
    KT("Kazakhstan"),
    KU("Kuwait"),
    KZ("Kyrgyzstan"),
    LB("Liberia"),
    LD("Moldova"),
    LE("Lesotho"),
    LF("Slovakia"),
    LH("Lithuania"),
    LI("Liechtenstein"),
    LN("Lebanon"),
    LO("Slovenia"),
    LS("Laos"),
    LU("Saint Lucia"),
    LX("Luxembourg"),
    LY("Libya"),
    MF("Malawi"),
    MG("Mongolia"),
    MJ("Monaco"),
    ML("Mali"),
    MM("Mexico"),
    MP("Madagascar/Malagasy Republic"),
    MQ("Morocco"),
    MU("Mauritania"),
    MV("Maldives"),
    MY("Malta"),
    MZ("Malaysia"),
    NE("Holland/Netherlands"),
    NG("Nigeria"),
    NI("Northern Ireland"),
    NN("Niger"),
    NO("New Guinea/Papua New Guinea"),
    NP("Nepal"),
    NQ("New Caledonia"),
    NR("Nauru"),
    NU("Nicaragua"),
    NW("Norway"),
    NX("Netherlands Antilles"),
    NZ("New Zealand"),
    OC("Macao/Macau"),
    OF("Norfolk Island"),
    OI("Okinawa"),
    OM("Oman"),
    OT("Oneida Indian Tribes of Wisconsin"),
    PC("Pitcairn Islands/Pitcairn Henderson Ducie & Oeno Isl.(Dep. territor"),
    PD("Republic of Palau"),
    PF("Parcel Islands"),
    PG("Guinea-Bissau/Portugese Guinea"),
    PI("Philippines"),
    PK("Pakistan"),
    PM("Panama"),
    PO("Poland"),
    PS("Miquelon/Saint Pierre"),
    PT("Portugal"),
    PU("Peru"),
    PV("Paraguay"),
    QA("Qatar"),
    RA("Russia"),
    RB("Brazzaville/Republic of Congo"),
    RC("People's Republic of China"),
    RE("Reunion"),
    RF("Russian Federation"),
    RG("Gibraltar"),
    RH("Rhodesia/Zimbabwe"),
    RR("Montserrat"),
    RS("Spanish Sahara/Western Sahara"),
    RU("Romania"),
    RV("Socialist Republic of Vietnam"),
    RW("Rwanda"),
    RY("Republic of Yemen"),
    SA("Sierre Leone/Sierra Leone"),
    SB("Saudi Arabia"),
    SE("Seychelles"),
    SF("South Africa"),
    SG("Senegal"),
    SH("San Marino"),
    SJ("Namibia/South-West Africa"),
    SM("Somalia"),
    SP("Spain"),
    SQ("Sweden"),
    SR("Singapore"),
    SS("Scotland"),
    ST("People's Democratic Rep. of Yemen/Southern Yemen"),
    SU("Sudan"),
    SV("Svalbard"),
    SW("Swaziland"),
    SX("Russia/USSR/Soviet Union/USSR"),
    SY("Syria"),
    SZ("Switzerland"),
    TC("Trucial States/United Arab Emirates"),
    TD("Trust Territory/Pacific Islands"),
    TE("Spratly Islands"),
    TF("Tuamotu Archipelago"),
    TG("Tonga"),
    TH("Thailand"),
    TJ("Tajikistan"),
    TK("Tokelau"),
    TM("Tromelin Island"),
    TO("Togo"),
    TP("Principe/Sao Tome"),
    TQ("Tongareva Island"),
    TR("Turks & Caicos Islands"),
    TS("Nevis/Saint Christopher/Saint Kitts"),
    TT("Tobago/Trinidad"),
    TU("Tunisia"),
    TV("Ellice Islands/Tuvalu"),
    TW("Republic of China/Taiwan"),
    TY("Turkey"),
    TZ("United Republic of Tanzania"),
    UG("Uganda"),
    UK("Ukraine"),
    UM("Mauritius"),
    UR("Turkmenistan"),
    US("United States of America"),
    UV("Burkina Faso/Upper Volta/"),
    UY("Uraguay"),
    UZ("Uzbekistan"),
    VB("British Virgin Islands"),
    VM("Vietnam"),
    VN("North Vietnam"),
    VS("South Vietnam"),
    VV("Saint Vincent/The Grenadines"),
    VY("Vatican City"),
    VZ("Venezuela"),
    WB("West Bank"),
    WF("Futuna/Wallis"),
    WG("Federal Republic of Germany/West Germany"),
    WL("Wales"),
    WN("West Indies"),
    WS("Western Samoa"),
    XX("Unknown Place of Birth"),
    YE("Yemen Arab Republic"),
    YG("Yugoslavia"),
    YO("Mayotte"),
    YY("All Others"),
    ZB("Martinique"),
    ZC("Surinam"),
    ZD("Macedonia"),
    ZI("Canary Islands"),
    ZM("Zambia"),
    ZO("Mozambique"),
    ZR("Congo Kinshasa/Zaire");


    private final String value;

    Country(String v)
    {
        this.value = v;
    }

    public String toString()
    {
        return value;
    }
}
